package strategyi.view;

import java.util.Random;
import javax.swing.JOptionPane;
import strategyi.controller.Drugs_Controler;
import strategyi.controller.DrugsPlayer_Controler;
import strategyi.controller.Filehandler_HighScore;
import strategyi.controller.Turn_Accounter;

/**
 *
 * @author Bruger
 */
public class JPanelMafiaGame extends javax.swing.JPanel {

    private String currentCountry = "Denmark";

    private Turn_Accounter travelAmount = Turn_Accounter.getInstance();
    private DrugsPlayer_Controler drugsPlayerControler;
    private Drugs_Controler drugsControler;
    private Filehandler_HighScore highScorefileHandler;
    private String fileName;

    public JPanelMafiaGame(String name) {

        fileName = "highScore.txt";
        initComponents();
        drugsPlayerControler = new DrugsPlayer_Controler();
        highScorefileHandler = new Filehandler_HighScore();

        highScorefileHandler.loadHighScore(fileName);
        drugsControler = new Drugs_Controler();

        jTextAreaAllDrugs.setText(drugsControler.allDrugstoString());
        jTextAreaPlayer.setText(drugsPlayerControler.drugsPlayerToString());

        jComboBoxDrugs.addItem("LIST OF DRUGS");
        jComboBoxDrugs.addItem("Cocaine");
        jComboBoxDrugs.addItem("Heroin");
        jComboBoxDrugs.addItem("Amphetamine");
        jComboBoxDrugs.addItem("Acid");
        jComboBoxDrugs.addItem("Angel dust");
        jComboBoxDrugs.addItem("Crystal Meth");
        jComboBoxDrugs.addItem("Hash");
        jComboBoxDrugs.addItem("weed");
        jComboBoxDrugs.addItem("Mushrooms");
        jComboBoxDrugs.addItem("Valium");

        jComboBoxCountry.addItem("LIST OF COUNTRY");
        jComboBoxCountry.addItem("Denmark");
        jComboBoxCountry.addItem("Colombia");
        jComboBoxCountry.addItem("Germany");
        jComboBoxCountry.addItem("USA");
        jComboBoxCountry.addItem("France");
        jComboBoxCountry.addItem("Afghanistan");

        drugsPlayerControler.setPlayername(name);
        jLabelPlayerMoney.setText("  " + drugsPlayerControler.getPlayername() + " : " + drugsPlayerControler.getPlayerMoney());
        jLabelCountryMassage.setText("You are ind: " + currentCountry);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBuy = new javax.swing.JButton();
        jButtonSale = new javax.swing.JButton();
        jComboBoxDrugs = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPlayer = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAllDrugs = new javax.swing.JTextArea();
        jButtonTRAVEL = new javax.swing.JButton();
        jLabelMassage = new javax.swing.JLabel();
        jLabelTur = new javax.swing.JLabel();
        jLabelPlayerMoney = new javax.swing.JLabel();
        jLabelCountryMassage = new javax.swing.JLabel();
        jComboBoxCountry = new javax.swing.JComboBox<>();

        jButtonBuy.setText("BUY");
        jButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuyActionPerformed(evt);
            }
        });

        jButtonSale.setText("SALE");
        jButtonSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaleActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount Of Drugs");

        jTextAreaPlayer.setColumns(20);
        jTextAreaPlayer.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPlayer);

        jTextAreaAllDrugs.setColumns(20);
        jTextAreaAllDrugs.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAllDrugs);

        jButtonTRAVEL.setText("Travel");
        jButtonTRAVEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTRAVELActionPerformed(evt);
            }
        });

        jLabelMassage.setForeground(new java.awt.Color(204, 0, 51));

        jLabelTur.setForeground(new java.awt.Color(204, 0, 204));

        jLabelPlayerMoney.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabelCountryMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelTur, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonTRAVEL, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSale, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelPlayerMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabelMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTur, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCountryMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(jButtonTRAVEL)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuy)
                    .addComponent(jButtonSale))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelPlayerMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabelMassage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuyActionPerformed
        // TODO add your handling code here:
        jLabelPlayerMoney.setText("  " + drugsPlayerControler.getPlayername() + " : " + drugsPlayerControler.getPlayerMoney());
        try {
            if (jTextFieldAmount.getText().equals("")) {
                jLabelMassage.setText("Please choise amount of drugs");
            } else if (jComboBoxDrugs.getSelectedItem().equals("LIST OF DRUGS")) {
                jLabelMassage.setText("Please choise the drugs");
            } else if (travelAmount.getTurn() <= 18) {
                jLabelMassage.setText("");
                int amount = Integer.parseInt(jTextFieldAmount.getText());
                String key = jComboBoxDrugs.getSelectedItem().toString();

                int price = drugsControler.getDrugs(key).getPrice();
                int avail = drugsControler.getDrugs(key).getAvailability();

                if (amount <= avail) {
                    int totalprice = amount * price;

                    if (totalprice <= drugsPlayerControler.getPlayerMoney()) {
                        jLabelMassage.setText("");
                        drugsPlayerControler.setPlayerMoney(drugsPlayerControler.getPlayerMoney() - totalprice);
                        drugsPlayerControler.increase(key, amount);
                        drugsControler.decrease(key, amount);

                        jTextAreaPlayer.setText(drugsPlayerControler.drugsPlayerToString());
                        jTextAreaAllDrugs.setText(drugsControler.allDrugstoString());

                    } else {
                        jLabelMassage.setText("you dont have enouf money to buy this stof");
                    }
                } else {
                    jLabelMassage.setText("you can only buy :" + avail);
                }
            } else {
                jLabelMassage.setText("In this turn you can only sale");
            }
        } catch (NumberFormatException e) {
            jLabelMassage.setText(" YOUR INPUT IS NOT VALID");
        }

        jLabelPlayerMoney.setText("  " + drugsPlayerControler.getPlayername() + " : " + drugsPlayerControler.getPlayerMoney());

    }//GEN-LAST:event_jButtonBuyActionPerformed

    private void jButtonSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaleActionPerformed
        // TODO add your handling code here:
        jLabelPlayerMoney.setText("  " + drugsPlayerControler.getPlayername() + " : " + drugsPlayerControler.getPlayerMoney());
        try {
            if (jTextFieldAmount.getText().equals("") || jComboBoxDrugs.getSelectedItem().equals("LIST OF DRUGS")) {
                jLabelMassage.setText("Please choise the drugs & amount of drugs");
            } else {
                jLabelMassage.setText("");
                int amount = Integer.parseInt(jTextFieldAmount.getText());
                String key = jComboBoxDrugs.getSelectedItem().toString();

                int price = drugsControler.getDrugs(key).getPrice();

                if (amount <= drugsPlayerControler.getValue(key)) {

                    int totalprice = amount * price;

                    drugsPlayerControler.setPlayerMoney(drugsPlayerControler.getPlayerMoney() + totalprice);
                    drugsPlayerControler.decrease(key, amount);
                    drugsControler.increase(key, amount);

                    jTextAreaAllDrugs.setText(drugsControler.allDrugstoString());
                    jTextAreaPlayer.setText(drugsPlayerControler.drugsPlayerToString());

                } else {
                    jLabelMassage.setText(" you can not sale more then you have");
                }
            }
        } catch (NumberFormatException e) {

            jLabelMassage.setText(" YOUR INPUT IS NOT VALID");
        }
        jLabelPlayerMoney.setText("  " + drugsPlayerControler.getPlayername() + " : " + drugsPlayerControler.getPlayerMoney());


    }//GEN-LAST:event_jButtonSaleActionPerformed

    private void jButtonTRAVELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTRAVELActionPerformed

        if (jComboBoxCountry.getSelectedItem().equals("LIST OF COUNTRY")) {

            jLabelMassage.setText("Please choose your country to travel");

        } else if (jComboBoxCountry.getSelectedItem().equals(currentCountry)) {

            jLabelMassage.setText("Please choose other country to travel, you are in " + currentCountry + " now");

        } else if (travelAmount.getTurn() < 19) {
            jLabelMassage.setText("");

            currentCountry = jComboBoxCountry.getSelectedItem().toString();
            jLabelCountryMassage.setText("You are in: " + currentCountry);

            drugsControler.calculateNewPriceAvail();// udregn ny pris og availability
            jTextAreaAllDrugs.setText(drugsControler.allDrugstoString());

            jLabelTur.setText("Travel amount is: " + (travelAmount.getTurn() + 1));
            travelAmount.setTurn();

        } else if (travelAmount.getTurn() == 19) {
            jLabelTur.setText("Travel amount is: " + (travelAmount.getTurn() + 1));

            if (drugsPlayerControler.drugsLastTurn()) {

                jLabelMassage.setText("IT IS LAST TRUN AND YOU STIL HAVE SOME DRUGS TO SALE");

            } else {

                jLabelMassage.setText("GAME OVER");
                highScorefileHandler.add(drugsPlayerControler.getPlayername(), drugsPlayerControler.getPlayerMoney());
                highScorefileHandler.saveScore(fileName);
                JOptionPane.showMessageDialog(null, highScorefileHandler.comparatorToString());

                //JOptionPane.showMessageDialog(null, highScorefileHandler.highScoreToString());
                travelAmount.setTurn();
            }
        } else {

            JOptionPane.showMessageDialog(null, "you can start play again");

        }
    }//GEN-LAST:event_jButtonTRAVELActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuy;
    private javax.swing.JButton jButtonSale;
    private javax.swing.JButton jButtonTRAVEL;
    private javax.swing.JComboBox<String> jComboBoxCountry;
    private javax.swing.JComboBox<String> jComboBoxDrugs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCountryMassage;
    private javax.swing.JLabel jLabelMassage;
    private javax.swing.JLabel jLabelPlayerMoney;
    private javax.swing.JLabel jLabelTur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaAllDrugs;
    private javax.swing.JTextArea jTextAreaPlayer;
    private javax.swing.JTextField jTextFieldAmount;
    // End of variables declaration//GEN-END:variables
}
